language: ruby

cache: bundler

sudo: false

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
  fast_finish: true

